'use client'

import { useMemo, useState } from 'react'
import { Accessibility, BarChart3, Check, GitCompare, MapPin, Menu, Search, ShieldCheck, Users, X, ArrowRight, ChevronDown } from 'lucide-react'

type Borough = 'Manhattan' | 'Brooklyn' | 'Queens' | 'The Bronx' | 'Staten Island'
interface Score { label: string; value: number }
interface Neighborhood { name: string; borough: Borough; rent: string; vibe: string; scores: Score[] }
interface Feature { icon: typeof MapPin; title: string; description: string }

const neighborhoods: Neighborhood[] = [
  { name: 'Astoria', borough: 'Queens', rent: '$2,600/mo', vibe: 'Lively', scores: [{ label: 'Affordability', value: 7 }, { label: 'Transit', value: 8 }, { label: 'Safety', value: 7 }] },
  { name: 'Riverdale', borough: 'The Bronx', rent: '$1,900/mo', vibe: 'Quiet', scores: [{ label: 'Affordability', value: 8 }, { label: 'Transit', value: 6 }, { label: 'Safety', value: 8 }] },
  { name: 'Park Slope', borough: 'Brooklyn', rent: '$3,200/mo', vibe: 'Mixed', scores: [{ label: 'Affordability', value: 5 }, { label: 'Transit', value: 9 }, { label: 'Safety', value: 8 }] },
]
const features: Feature[] = [
  { icon: MapPin, title: 'Interactive Map', description: 'Click any neighborhood on our NYC map to instantly see rent prices and scores.' },
  { icon: BarChart3, title: 'Smart Scoring', description: 'Six dimensions scored from 1–10: affordability, transit, safety, schools, accessibility and convenience.' },
  { icon: Users, title: 'Personalized Match', description: 'Tell us your budget, lifestyle and needs — we rank every neighborhood for you.' },
  { icon: Accessibility, title: 'Accessibility First', description: 'The first NYC tool with dedicated disability accessibility scoring for every neighborhood.' },
  { icon: ShieldCheck, title: 'Unbiased Data', description: 'Built on verified NYC government data — no real estate listing bias ever.' },
  { icon: GitCompare, title: 'Side by Side Compare', description: 'Compare any two neighborhoods across all metrics with visual radar charts.' },
]
const boroughs = [['Manhattan', '18 neighborhoods', '$3,950', 'Transit'], ['Brooklyn', '24 neighborhoods', '$3,200', 'Safety'], ['Queens', '21 neighborhoods', '$2,600', 'Affordability'], ['The Bronx', '15 neighborhoods', '$1,900', 'Affordability'], ['Staten Island', '9 neighborhoods', '$2,250', 'Safety']]

function Navbar() {
  const [open, setOpen] = useState(false)
  return <header className="sticky top-0 z-50 border-b border-border/80 bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="#top" className="text-xl font-bold tracking-tight text-foreground">NestMapper <span className="text-primary">NYC</span></a><nav className={`${open ? 'flex' : 'hidden'} absolute left-0 right-0 top-full flex-col gap-5 border-b border-border bg-background px-5 py-5 md:static md:flex md:flex-row md:items-center md:border-0 md:bg-transparent md:p-0`}><a href="#explore-form" className="nav-link">Explore</a><a href="/compare" className="nav-link">Compare</a><a href="/recommend" className="nav-link">Recommend</a><a href="#about" className="nav-link">About</a><a href="#explore-form" className="button-primary md:ml-3">Get Started</a></nav><button className="md:hidden" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X /> : <Menu />}</button></div></header>
}
function Hero() { return <section id="top" className="hero-grid mx-auto max-w-7xl px-5 pb-16 pt-16 lg:px-8 lg:pb-24 lg:pt-24"><div className="hero-copy"><div className="hero-kicker"><span className="kicker-dot" /> THE SMARTER WAY TO MOVE</div><h1 className="text-balance text-5xl font-bold leading-[1.02] tracking-tight text-foreground md:text-7xl">Find the neighborhood that feels like <span className="text-primary">home.</span></h1><p className="mt-7 max-w-xl text-pretty text-lg leading-8 text-muted-foreground">A clearer way to understand New York City. Compare rent, safety, transit, schools, and accessibility across all five boroughs.</p><div className="mt-9 flex flex-wrap gap-3"><a className="button-primary" href="#explore-form">Start exploring <ArrowRight data-icon="inline-end" /></a><a className="button-secondary" href="#recommend">See neighborhood scores</a></div><div className="mt-12 flex max-w-xl divide-x divide-border"><div className="stat"><strong>50+</strong><span>Neighborhoods</span></div><div className="stat"><strong>5</strong><span>Boroughs</span></div><div className="stat"><strong>6</strong><span>Score dimensions</span></div></div></div><div className="hero-visual"><div className="hero-mark" aria-hidden="true" /><div className="hero-note"><span className="hero-note-icon"><ShieldCheck /></span><span><strong>Built for better decisions</strong><small>Free, independent neighborhood data</small></span></div><div className="hero-location"><MapPin /><span>New York City<br /><strong>Know before you move</strong></span></div></div></section> }
function SearchBar() { const [query, setQuery] = useState(''); const [borough, setBorough] = useState('All Boroughs'); return <section id="explore" className="mx-auto max-w-7xl scroll-mt-20 px-5 py-10 lg:px-8"><div className="search-panel"><div className="flex flex-col gap-3 lg:flex-row"><label className="input-wrap"><Search aria-hidden="true" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search any NYC neighborhood..." aria-label="Search neighborhoods" /></label><label className="select-wrap"><select value={borough} onChange={e => setBorough(e.target.value)} aria-label="Filter by borough"><option>All Boroughs</option>{['Manhattan','Brooklyn','Queens','The Bronx','Staten Island'].map(b => <option key={b}>{b}</option>)}</select><ChevronDown aria-hidden="true" /></label><button className="button-primary justify-center">Search</button></div><div className="mt-6 flex flex-wrap items-center gap-2"><span className="mr-1 text-sm text-muted-foreground">Popular:</span>{['Astoria','Williamsburg','Harlem','Park Slope','Riverdale'].map(chip => <button key={chip} onClick={() => setQuery(chip)} className="chip">{chip}</button>)}</div><p className="mt-4 text-sm text-muted-foreground">{query || borough !== 'All Boroughs' ? `Showing matches for ${query || borough}` : 'Explore 50+ neighborhoods across New York City.'}</p></div></section> }
function ExploreFormSection() {
  const [budget, setBudget] = useState(2000)
  const [borough, setBorough] = useState('Any')
  const [transit, setTransit] = useState(3)
  const [situation, setSituation] = useState('Professional')
  const [priority, setPriority] = useState('Affordability')

  return <section id="explore-form" className="mx-auto max-w-7xl scroll-mt-20 px-5 py-10 lg:px-8">
    <div className="explore-split">
      <div className="preference-card">
        <p className="eyebrow">FIND YOUR NEIGHBORHOOD</p>
        <h2>Tell us what matters to you</h2>
        <p className="preference-subtitle">Get matched in seconds</p>
        <div className="preference-group">
          <div className="preference-label"><span>Monthly Budget</span><strong>${budget.toLocaleString()}/mo</strong></div>
          <input className="budget-range" type="range" min="500" max="5000" step="100" value={budget} onChange={e => setBudget(Number(e.target.value))} aria-label="Monthly budget" />
        </div>
        <div className="preference-group"><span className="preference-title">Preferred Borough</span><div className="pill-row">{['Any','Manhattan','Brooklyn','Queens','Bronx','Staten Island'].map(item => <button key={item} type="button" onClick={() => setBorough(item)} className={`preference-pill ${borough === item ? 'selected' : ''}`}>{item}</button>)}</div></div>
        <div className="preference-group"><span className="preference-title">Transit Priority</span><div className="pill-row">{[1,2,3,4,5].map(item => <button key={item} type="button" onClick={() => setTransit(item)} className={`preference-pill compact ${transit === item ? 'selected' : ''}`}>{item}</button>)}</div></div>
        <div className="preference-group"><span className="preference-title">I am a...</span><div className="pill-row">{['Student','Professional','Family','Couple'].map(item => <button key={item} type="button" onClick={() => setSituation(item)} className={`preference-pill ${situation === item ? 'selected' : ''}`}>{item}</button>)}</div></div>
        <div className="preference-group"><span className="preference-title">Most Important <small>(choose up to 3)</small></span><div className="pill-row">{['Affordability','Safety','Transit','Schools','Accessibility','Parks'].map(item => <button key={item} type="button" onClick={() => setPriority(item)} className={`preference-pill ${priority === item ? 'selected' : ''}`}>{priority === item && <Check aria-hidden="true" />} {item}</button>)}</div></div>
        <div className="preference-group"><span className="preference-title">Special Needs</span><div className="needs-list">{['Accessibility needed','Own a car','Have children'].map(item => <label key={item} className="need-row"><span>{item}</span><input type="checkbox" aria-label={item} /></label>)}</div></div>
        <a href="/recommend" className="button-primary preference-submit">Find My Neighborhood <ArrowRight data-icon="inline-end" /></a>
      </div>
      <div className="live-map-card" aria-label="Live map preview showing neighborhood matches">
        <div className="map-preview-copy"><p className="eyebrow"><MapPin data-icon="inline-start" /> LIVE MAP PREVIEW</p><h2>See your matches<br /> on the map</h2><p>Explore color-coded neighborhoods across New York City.</p></div>
        <div className="map-orb orb-cyan" /><div className="map-orb orb-green" /><div className="map-orb orb-amber" /><div className="map-orb orb-red" /><MapPin className="preview-pin" aria-hidden="true" />
      </div>
    </div>
  </section>
}
function Features() { return <section id="about" className="section-wrap"><div className="section-heading section-heading-split"><div><p className="eyebrow">BUILT AROUND YOUR LIFE</p><h2>Everything You Need<br className="hidden md:block" /> to Find Your Home</h2></div><p className="section-heading-note">Less guesswork. More confidence in where your next chapter begins.</p></div><div className="feature-grid">{features.map(({ icon: Icon, title, description }) => <article className="feature-card" key={title}><Icon className="text-primary" /><h3>{title}</h3><p>{description}</p></article>)}</div></section> }
function HowItWorks() { return <section id="compare" className="section-wrap compare-section border-y border-border bg-card/30"><div className="section-heading section-heading-split"><div><p className="eyebrow">A CLEARER PATH HOME</p><h2>How NestMapper NYC Works</h2></div><p className="section-heading-note">Three simple ways to turn city data into a decision you can feel good about.</p></div><div className="steps">{[['01','Explore the Map','Browse our interactive NYC map and click any neighborhood to see its full profile'],['02','Compare Options','Select two neighborhoods and compare them side by side across all 6 dimensions'],['03','Get Your Match','Fill in your preferences and our algorithm finds your perfect neighborhood instantly']].map(([number,title,description], i) => <div className="step" key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p>{i < 2 && <ArrowRight className="step-arrow" aria-hidden="true" />}</div>)}</div></section> }
function NeighborhoodCard({ data }: { data: Neighborhood }) { return <article className="neighborhood-card"><div className="flex items-start justify-between"><div><p className="text-sm text-primary">{data.borough}</p><h3>{data.name}</h3></div><span className="vibe">{data.vibe}</span></div><div className="scores">{data.scores.map(score => <div key={score.label}><div className="mb-2 flex justify-between text-sm"><span>{score.label}</span><strong>{score.value}/10</strong></div><div className="score-track"><div className={`score-fill ${score.value < 4 ? 'low' : score.value < 7 ? 'medium' : ''}`} style={{ width: `${score.value * 10}%` }} /></div></div>)}</div><div className="mt-7 flex items-center justify-between border-t border-border pt-5"><div><span className="block text-xs text-muted-foreground">AVG 1BR</span><strong className="text-lg">{data.rent}</strong></div><a href="#explore-form" className="text-sm font-semibold text-primary hover:underline">View Full Profile</a></div></article> }
function BoroughSection() { return <section className="section-wrap"><div className="section-heading"><p className="eyebrow">THE FIVE BOROUGHS</p><h2>Explore All 5 Boroughs</h2></div><div className="borough-grid">{boroughs.map(([name,count,rent,score]) => <a className="borough-card" href="#explore-form" key={name}><h3>{name}</h3><p>{count}</p><div className="mt-7 flex justify-between text-sm"><span><b>{rent}</b><small> avg rent</small></span><span><b>{score}</b><small> top score</small></span></div></a>)}</div></section> }
function App() { const [query] = useState(''); const filtered = useMemo(() => neighborhoods.filter(n => !query || n.name.toLowerCase().includes(query.toLowerCase())), [query]); return <><Navbar /><main><Hero /><ExploreFormSection /><Features /><HowItWorks /><section id="recommend" className="section-wrap recommend-section"><div className="section-heading flex-row section-heading-split"><div><p className="eyebrow">START SOMEWHERE GOOD</p><h2>Featured Neighborhoods</h2></div><p className="section-heading-note">A quick look at places worth putting on your shortlist.</p><a href="#explore-form" className="text-sm font-semibold text-primary">View all neighborhoods <ArrowRight className="ml-1 inline" size={16} /></a></div><div className="neighborhood-grid">{(filtered.length ? filtered : neighborhoods).map(n => <NeighborhoodCard data={n} key={n.name} />)}</div></section><BoroughSection /><section className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="cta"><div><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>Ready to Find Your<br className="hidden md:block" /> Perfect Neighborhood?</h2><p>Join thousands of New Yorkers making smarter housing decisions with NestMapper NYC</p></div><div><a href="#explore-form" className="button-light">Start Exploring Free <ArrowRight data-icon="inline-end" /></a><small>No account required — completely free forever</small></div></div></section></main><footer><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-10 lg:px-8 md:flex-row md:items-end md:justify-between"><div><a href="#top" className="text-xl font-bold">NestMapper <span className="text-primary">NYC</span></a><p className="mt-2 text-sm text-muted-foreground">Know Before You Move</p></div><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm text-muted-foreground"><a href="#explore-form">Explore</a><a href="#compare">Compare</a><a href="#recommend">Recommend</a><a href="#about">About</a><a href="#">GitHub</a></div><div className="text-left text-sm text-muted-foreground md:text-right"><p>Data: NYC Open Data · MTA · NYC DOE</p><p className="mt-2">© 2026 NestMapper NYC · Built for New Yorkers by New Yorkers</p></div></div></footer></> }
export default App
