# Generated by Django 6.1 on 2026-09-02 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('borough', models.CharField(choices=[('Manhattan', 'Manhattan'), ('Brooklyn', 'Brooklyn'), ('Queens', 'Queens'), ('The Bronx', 'The Bronx'), ('Staten Island', 'Staten Island')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('vibe', models.CharField(choices=[('Quiet', 'Quiet'), ('Lively', 'Lively'), ('Mixed', 'Mixed')], default='Mixed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['borough', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schools_count', models.IntegerField(default=0)),
                ('hospitals_count', models.IntegerField(default=0)),
                ('parks_count', models.IntegerField(default=0)),
                ('grocery_stores_count', models.IntegerField(default=0)),
                ('restaurants_count', models.IntegerField(default=0)),
                ('pharmacies_count', models.IntegerField(default=0)),
                ('neighborhood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='AccessibilityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_elevator_station', models.BooleanField(default=False, help_text='Does nearest subway station have elevator?')),
                ('ada_intersections', models.IntegerField(default=0, help_text='Number of ADA compliant intersections')),
                ('accessible_parks', models.IntegerField(default=0, help_text='Number of wheelchair accessible parks')),
                ('accessibility_notes', models.TextField(blank=True, help_text='Any additional accessibility information')),
                ('neighborhood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility', to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='NeighborhoodScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affordability_score', models.FloatField(default=0)),
                ('transit_score', models.FloatField(default=0)),
                ('safety_score', models.FloatField(default=0)),
                ('family_score', models.FloatField(default=0)),
                ('accessibility_score', models.FloatField(default=0)),
                ('convenience_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('neighborhood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard'), ('Very Hard', 'Very Hard')], default='Moderate', max_length=20)),
                ('avg_monthly_garage_cost', models.IntegerField(blank=True, help_text='Average monthly garage cost in USD', null=True)),
                ('street_parking_available', models.BooleanField(default=True)),
                ('parking_notes', models.TextField(blank=True)),
                ('neighborhood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='RentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio', models.IntegerField(help_text='Average studio rent in USD')),
                ('one_bedroom', models.IntegerField(help_text='Average 1BR rent in USD')),
                ('two_bedroom', models.IntegerField(help_text='Average 2BR rent in USD')),
                ('three_bedroom', models.IntegerField(blank=True, help_text='Average 3BR rent in USD', null=True)),
                ('neighborhood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_index', models.FloatField(help_text='Raw crime index from NYC Open Data')),
                ('borough_avg_crime', models.FloatField(help_text='Borough average crime index for comparison')),
                ('felony_count', models.IntegerField(blank=True, help_text='Annual felony count', null=True)),
                ('misdemeanor_count', models.IntegerField(blank=True, help_text='Annual misdemeanor count', null=True)),
                ('neighborhood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety', to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='TransitInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subway_lines', models.JSONField(default=list, help_text="List of subway lines e.g ['A','C','E']")),
                ('bus_routes', models.JSONField(default=list, help_text="List of bus routes e.g ['M15','M79']")),
                ('nearest_station', models.CharField(max_length=100)),
                ('walk_score', models.IntegerField(help_text='Walkability score 0-100')),
                ('transit_score', models.IntegerField(help_text='Transit score 0-100')),
                ('neighborhood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transit', to='neighborhoods.neighborhood')),
            ],
        ),
    ]
